// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByY0VOCuiL-cgfY8W41Vn-Qk1DWxg-AEI',
    appId: '1:513823144550:web:5269c4fd040ff111484ba7',
    messagingSenderId: '513823144550',
    projectId: 'servir-c4cf6',
    authDomain: 'servir-c4cf6.firebaseapp.com',
    storageBucket: 'servir-c4cf6.firebasestorage.app',
    measurementId: 'G-G0J874XCM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbu9G5FmTWvDlapjOK6iUNz_-NB_YsHA',
    appId: '1:513823144550:android:9179f323c115747b484ba7',
    messagingSenderId: '513823144550',
    projectId: 'servir-c4cf6',
    storageBucket: 'servir-c4cf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-ZbtHtSzlaF2SZWUhPKfvrmcfpQV2Bk',
    appId: '1:513823144550:ios:37f67246202977df484ba7',
    messagingSenderId: '513823144550',
    projectId: 'servir-c4cf6',
    storageBucket: 'servir-c4cf6.firebasestorage.app',
    iosBundleId: 'com.servir.app.servir',
  );
}
